# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - eshoes-basket

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: eshoes-basket
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-deploy:
    runs-on: 
      ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # To get JWT
      contents: read   # To read repository (checkout)
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./Services/Ecommerce.Basket/Ecommerce.Basket.Api/Ecommerce.Basket.Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./Services/Ecommerce.Basket/Ecommerce.Basket.Api/Ecommerce.Basket.Api.csproj -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1735B1EB0CC7499A92F53456566D0878 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1F5427BFAA2342969D97397FCB4929AC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_223BEE566E1B4606A0304367A9C85A2E }}

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp/appsettings.json'
        env:
          Redis.DefaultConnection: ${{ secrets.REDIS_CONNECTION }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp
          
