# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: eshoes-orders deploy .netCore Api to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: eshoes-orders
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # To get JWT
      contents: read   # To read repository (checkout)

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./Services/Ecommerce.Orders/Ecommerce.Orders.Api/Ecommerce.Orders.Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./Services/Ecommerce.Orders/Ecommerce.Orders.Api/Ecommerce.Orders.Api.csproj -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_27B9573C1C354F08B2C76038C03FF04F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_239381C08ABB4F92AA801187775016BE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_98993ECD74D94E6191D5EC3225C4FECA }}

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp/appsettings.json'
        env:
          ConnectionStrings.OrdersDatabase: ${{ secrets.DB_ORDERS_CONNECTION_STRING }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp
          