# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: eshoes-catalog deploy .netCore Api to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: eshoes-catalog
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # To get JWT
      contents: read   # To read repository (checkout)

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./Services/Ecommerce.Catalog/Ecommerce.Catalog.Api/Ecommerce.Catalog.Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./Services/Ecommerce.Catalog/Ecommerce.Catalog.Api/Ecommerce.Catalog.Api.csproj -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_166B87597A4B4D048A7C5F9550E3E8CE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2E2DA548283249538F0FD182887DB5FA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5BE9127FA2C04C1FA548BF9530ED1FE6 }}

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp/appsettings.json'
        env:
          ConnectionStrings.CatalogDatabase: ${{secrets.DB_CATALOG_CONNECTION_STRING}}
          AzureStorage.ConnectionString: ${{secrets.AZURE_CONNECTION}}
          AzureStorage.ShareName: ${{secrets.AZURE_SHARE_NAME}}
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp
          
